### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Zezeq** [wikijm/PowerShell-AdminScripts#2]
Is it possible to assign a license to the repository? I found your scripts when using google to find a solution to a problem I was having and if it was possible I would like to use some of your script as open source.

**Comment by wikijm** [comment]
Hi @Zezeq,

Thanks for the interest you have for this repo!
I've just added license into the README.md: https://github.com/wikijm/PowerShell-AdminScripts/commit/ebfc41783eab0ea3f42e7d3402936bf7270c8d1f

On which project would you like to reuse my code?
I'm just curious, I don't want to say yes or no depending to the project 😉
